[QdrantClient]
url = "https://02702cd9-b8bb-4785-bf59-ab7c327443d8.us-east4-0.gcp.cloud.qdrant.io:6333"
port = 6333
api_key = "_sYptKewmRFnn7bSMfU1DZP1kEz3KXuJ6TzKLfD1-B5LaWfw71kE8w"

[OpenAI]
api_key = "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"
